// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addresses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (
    user_id, label, line1, line2, city, state, postal_code, country, is_default
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, label, line1, line2, city, state, postal_code, country, is_default, is_deleted, created_at, updated_at
`

type CreateAddressParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Label      pgtype.Text `json:"label"`
	Line1      string      `json:"line1"`
	Line2      pgtype.Text `json:"line2"`
	City       string      `json:"city"`
	State      string      `json:"state"`
	PostalCode string      `json:"postal_code"`
	Country    string      `json:"country"`
	IsDefault  pgtype.Bool `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Label,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
UPDATE addresses
SET is_deleted=true,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddress = `-- name: GetAddress :one
SELECT id, user_id, label, line1, line2, city, state, postal_code, country, is_default, is_deleted, created_at, updated_at FROM addresses
WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetAddress(ctx context.Context, id pgtype.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddress, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressesByUser = `-- name: GetAddressesByUser :many
SELECT id, user_id, label, line1, line2, city, state, postal_code, country, is_default, is_deleted, created_at, updated_at FROM addresses
WHERE user_id = $1 AND is_deleted = false
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) GetAddressesByUser(ctx context.Context, userID pgtype.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, getAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.IsDefault,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET label = COALESCE($2, label),
    line1 = COALESCE($3, line1),
    line2 = COALESCE($4, line2),
    city = COALESCE($5, city),
    state = COALESCE($6, state),
    postal_code = COALESCE($7, postal_code),
    country = COALESCE($8, country),
    is_default = COALESCE($9, is_default),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, label, line1, line2, city, state, postal_code, country, is_default, is_deleted, created_at, updated_at
`

type UpdateAddressParams struct {
	ID         pgtype.UUID `json:"id"`
	Label      pgtype.Text `json:"label"`
	Line1      string      `json:"line1"`
	Line2      pgtype.Text `json:"line2"`
	City       string      `json:"city"`
	State      string      `json:"state"`
	PostalCode string      `json:"postal_code"`
	Country    string      `json:"country"`
	IsDefault  pgtype.Bool `json:"is_default"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Label,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
