// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id, expires_at)
VALUES ($1, $2)
RETURNING id, user_id, expires_at, created_at, updated_at
`

type CreateCartParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, arg.UserID, arg.ExpiresAt)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts
WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCart, id)
	return err
}

const deleteExpiredCarts = `-- name: DeleteExpiredCarts :exec
DELETE FROM carts
WHERE expires_at IS NOT NULL
  AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredCarts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCarts)
	return err
}

const getCartByID = `-- name: GetCartByID :one
SELECT id, user_id, expires_at, created_at, updated_at
FROM carts
WHERE id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

func (q *Queries) GetCartByID(ctx context.Context, id pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByID, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, expires_at, created_at, updated_at
FROM carts
WHERE user_id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCarts = `-- name: ListCarts :many
SELECT id, user_id, expires_at, created_at, updated_at
FROM carts
WHERE expires_at IS NULL OR expires_at > NOW()
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCartsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCarts(ctx context.Context, arg ListCartsParams) ([]Cart, error) {
	rows, err := q.db.Query(ctx, listCarts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCart = `-- name: UpdateCart :one
UPDATE carts
SET 
    expires_at = COALESCE($2, expires_at),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, expires_at, created_at, updated_at
`

type UpdateCartParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateCart(ctx context.Context, arg UpdateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCart, arg.ID, arg.ExpiresAt)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
