// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (cart_id, product_id)
DO UPDATE SET
    quantity = EXCLUDED.quantity,
    created_at = NOW()
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type AddCartItemParams struct {
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
	Quantity  int32       `json:"quantity"`
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addCartItems = `-- name: AddCartItems :many
INSERT INTO cart_items (id, cart_id, product_id, quantity, created_at, updated_at)
SELECT
    gen_random_uuid() AS id,
    $1 AS cart_id,
    p.product_id,
    p.quantity,
    NOW() AS created_at,
    NOW() AS updated_at
FROM (
    SELECT unnest($2::uuid[]) AS product_id,
           unnest($3::int[]) AS quantity
) AS p(product_id, quantity)
ON CONFLICT (cart_id, product_id)
DO UPDATE SET
    quantity = EXCLUDED.quantity,  
    updated_at = NOW()
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type AddCartItemsParams struct {
	CartID  pgtype.UUID   `json:"cart_id"`
	Column2 []pgtype.UUID `json:"column_2"`
	Column3 []int32       `json:"column_3"`
}

func (q *Queries) AddCartItems(ctx context.Context, arg AddCartItemsParams) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, addCartItems, arg.CartID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE id = $1
`

func (q *Queries) DeleteCartItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItem, id)
	return err
}

const deleteCartItemsByCart = `-- name: DeleteCartItemsByCart :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) DeleteCartItemsByCart(ctx context.Context, cartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCartItemsByCart, cartID)
	return err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, cart_id, product_id, quantity, created_at, updated_at
FROM cart_items
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCartItem(ctx context.Context, id pgtype.UUID) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByProduct = `-- name: GetCartItemByProduct :one
SELECT id, cart_id, product_id, quantity, created_at, updated_at
FROM cart_items
WHERE cart_id = $1
  AND product_id = $2
LIMIT 1
`

type GetCartItemByProductParams struct {
	CartID    pgtype.UUID `json:"cart_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByProduct, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemsByUserID = `-- name: GetCartItemsByUserID :many
SELECT ci.id, ci.cart_id, ci.product_id, ci.quantity, ci.created_at, ci.updated_at
FROM cart_items ci
JOIN carts c ON ci.cart_id = c.id
WHERE c.user_id = $1
ORDER BY ci.created_at ASC
`

func (q *Queries) GetCartItemsByUserID(ctx context.Context, userID pgtype.UUID) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, getCartItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, cart_id, product_id, quantity, created_at, updated_at
FROM cart_items
WHERE cart_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCartItems(ctx context.Context, cartID pgtype.UUID) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET 
    quantity = $2,
    created_at = NOW()
WHERE id = $1
RETURNING id, cart_id, product_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	ID       pgtype.UUID `json:"id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
