// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupons.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCoupons = `-- name: CountCoupons :one
SELECT COUNT(*) FROM coupons
`

func (q *Queries) CountCoupons(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCoupons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
    code, description, discount_percent, valid_from, valid_until, max_uses, is_active
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, code, description, discount_percent, valid_from, valid_until, max_uses, used_count, is_active, is_deleted, created_at, updated_at
`

type CreateCouponParams struct {
	Code            string             `json:"code"`
	Description     pgtype.Text        `json:"description"`
	DiscountPercent int32              `json:"discount_percent"`
	ValidFrom       pgtype.Timestamptz `json:"valid_from"`
	ValidUntil      pgtype.Timestamptz `json:"valid_until"`
	MaxUses         pgtype.Int4        `json:"max_uses"`
	IsActive        pgtype.Bool        `json:"is_active"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.Code,
		arg.Description,
		arg.DiscountPercent,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.MaxUses,
		arg.IsActive,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.DiscountPercent,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.MaxUses,
		&i.UsedCount,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoupon = `-- name: DeleteCoupon :exec
DELETE FROM coupons
WHERE id = $1
`

func (q *Queries) DeleteCoupon(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoupon, id)
	return err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, description, discount_percent, valid_from, valid_until, max_uses, used_count, is_active, is_deleted, created_at, updated_at FROM coupons
WHERE code = $1
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.DiscountPercent,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.MaxUses,
		&i.UsedCount,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponById = `-- name: GetCouponById :one
SELECT id, code, description, discount_percent, valid_from, valid_until, max_uses, used_count, is_active, is_deleted, created_at, updated_at FROM coupons
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCouponById(ctx context.Context, id pgtype.UUID) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponById, id)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.DiscountPercent,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.MaxUses,
		&i.UsedCount,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoupons = `-- name: GetCoupons :many
SELECT id, code, description, discount_percent, valid_from, valid_until, max_uses, used_count, is_active, is_deleted, created_at, updated_at FROM coupons
LIMIT $1 OFFSET $2
`

type GetCouponsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetCoupons(ctx context.Context, arg GetCouponsParams) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, getCoupons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.DiscountPercent,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.MaxUses,
			&i.UsedCount,
			&i.IsActive,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCouponUsage = `-- name: IncrementCouponUsage :one
UPDATE coupons
SET used_count = used_count + 1,
    updated_at = NOW()
WHERE code = $1
RETURNING id, code, description, discount_percent, valid_from, valid_until, max_uses, used_count, is_active, is_deleted, created_at, updated_at
`

func (q *Queries) IncrementCouponUsage(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, incrementCouponUsage, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.DiscountPercent,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.MaxUses,
		&i.UsedCount,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCoupon = `-- name: UpdateCoupon :one
UPDATE coupons
SET code = COALESCE($2, code),
    description = COALESCE($3, description),
    discount_percent = COALESCE($4, discount_percent),
    valid_from = COALESCE($5, valid_from),
    valid_until = COALESCE($6, valid_until),
    max_uses = COALESCE($7, max_uses),
    is_active = COALESCE($8, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, description, discount_percent, valid_from, valid_until, max_uses, used_count, is_active, is_deleted, created_at, updated_at
`

type UpdateCouponParams struct {
	ID              pgtype.UUID        `json:"id"`
	Code            string             `json:"code"`
	Description     pgtype.Text        `json:"description"`
	DiscountPercent int32              `json:"discount_percent"`
	ValidFrom       pgtype.Timestamptz `json:"valid_from"`
	ValidUntil      pgtype.Timestamptz `json:"valid_until"`
	MaxUses         pgtype.Int4        `json:"max_uses"`
	IsActive        pgtype.Bool        `json:"is_active"`
}

func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, updateCoupon,
		arg.ID,
		arg.Code,
		arg.Description,
		arg.DiscountPercent,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.MaxUses,
		arg.IsActive,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.DiscountPercent,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.MaxUses,
		&i.UsedCount,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
