// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventory (
    product_id,
    stock,
    reserved
) VALUES (
    $1, $2, $3
) RETURNING product_id, stock, reserved, created_at, updated_at
`

type CreateInventoryParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Stock     int32       `json:"stock"`
	Reserved  int32       `json:"reserved"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory, arg.ProductID, arg.Stock, arg.Reserved)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Stock,
		&i.Reserved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInventory = `-- name: DeleteInventory :exec
DELETE FROM inventory
WHERE product_id = $1
`

func (q *Queries) DeleteInventory(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInventory, productID)
	return err
}

const getInventoryByProductID = `-- name: GetInventoryByProductID :one
SELECT product_id, stock, reserved, created_at, updated_at FROM inventory
WHERE product_id = $1 LIMIT 1
`

func (q *Queries) GetInventoryByProductID(ctx context.Context, productID pgtype.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByProductID, productID)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Stock,
		&i.Reserved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInventoryStock = `-- name: UpdateInventoryStock :one
UPDATE inventory
SET 
    stock = $2,
    updated_at = NOW()
WHERE product_id = $1
RETURNING product_id, stock, reserved, created_at, updated_at
`

type UpdateInventoryStockParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Stock     int32       `json:"stock"`
}

func (q *Queries) UpdateInventoryStock(ctx context.Context, arg UpdateInventoryStockParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryStock, arg.ProductID, arg.Stock)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Stock,
		&i.Reserved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
