// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OtpType string

const (
	OtpTypeVerification  OtpType = "verification"
	OtpTypePasswordReset OtpType = "password_reset"
)

func (e *OtpType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OtpType(s)
	case string:
		*e = OtpType(s)
	default:
		return fmt.Errorf("unsupported scan type for OtpType: %T", src)
	}
	return nil
}

type NullOtpType struct {
	OtpType OtpType `json:"otp_type"`
	Valid   bool    `json:"valid"` // Valid is true if OtpType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOtpType) Scan(value interface{}) error {
	if value == nil {
		ns.OtpType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OtpType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOtpType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OtpType), nil
}

type UserRole string

const (
	UserRoleCustomer   UserRole = "customer"
	UserRoleAdmin      UserRole = "admin"
	UserRoleSuperadmin UserRole = "superadmin"
	UserRoleVendor     UserRole = "vendor"
	UserRoleSupport    UserRole = "support"
	UserRoleDelivery   UserRole = "delivery"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Address struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Label      pgtype.Text        `json:"label"`
	Line1      string             `json:"line1"`
	Line2      pgtype.Text        `json:"line2"`
	City       string             `json:"city"`
	State      string             `json:"state"`
	PostalCode string             `json:"postal_code"`
	Country    string             `json:"country"`
	IsDefault  pgtype.Bool        `json:"is_default"`
	IsDeleted  pgtype.Bool        `json:"is_deleted"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Details    []byte             `json:"details"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Cart struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CartItem struct {
	ID        pgtype.UUID        `json:"id"`
	CartID    pgtype.UUID        `json:"cart_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Description pgtype.Text        `json:"description"`
	IsDeleted   pgtype.Bool        `json:"is_deleted"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Coupon struct {
	ID              pgtype.UUID        `json:"id"`
	Code            string             `json:"code"`
	Description     pgtype.Text        `json:"description"`
	DiscountPercent int32              `json:"discount_percent"`
	ValidFrom       pgtype.Timestamptz `json:"valid_from"`
	ValidUntil      pgtype.Timestamptz `json:"valid_until"`
	MaxUses         pgtype.Int4        `json:"max_uses"`
	UsedCount       pgtype.Int4        `json:"used_count"`
	IsActive        pgtype.Bool        `json:"is_active"`
	IsDeleted       pgtype.Bool        `json:"is_deleted"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Inventory struct {
	ProductID pgtype.UUID        `json:"product_id"`
	Stock     int32              `json:"stock"`
	Reserved  int32              `json:"reserved"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	OrderNumber   string             `json:"order_number"`
	SubtotalCents int64              `json:"subtotal_cents"`
	DiscountCents pgtype.Int8        `json:"discount_cents"`
	TaxCents      pgtype.Int8        `json:"tax_cents"`
	ShippingCents pgtype.Int8        `json:"shipping_cents"`
	TotalCents    int64              `json:"total_cents"`
	FinalCents    int64              `json:"final_cents"`
	Currency      string             `json:"currency"`
	Status        string             `json:"status"`
	ShippingInfo  []byte             `json:"shipping_info"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID              pgtype.UUID        `json:"id"`
	OrderID         pgtype.UUID        `json:"order_id"`
	ProductID       pgtype.UUID        `json:"product_id"`
	Sku             pgtype.Text        `json:"sku"`
	Name            pgtype.Text        `json:"name"`
	Qty             int32              `json:"qty"`
	UnitPriceCents  int32              `json:"unit_price_cents"`
	TotalPriceCents int32              `json:"total_price_cents"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID            pgtype.UUID        `json:"id"`
	OrderID       pgtype.UUID        `json:"order_id"`
	Provider      string             `json:"provider"`
	ProviderTxnID pgtype.Text        `json:"provider_txn_id"`
	AmountCents   int64              `json:"amount_cents"`
	Currency      string             `json:"currency"`
	PaymentMethod string             `json:"payment_method"`
	Status        string             `json:"status"`
	Details       []byte             `json:"details"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID                 pgtype.UUID        `json:"id"`
	Sku                string             `json:"sku"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	PriceCents         int32              `json:"price_cents"`
	Currency           string             `json:"currency"`
	Attributes         []byte             `json:"attributes"`
	MainImageUrl       pgtype.Text        `json:"main_image_url"`
	Images             []byte             `json:"images"`
	DiscountPercent    pgtype.Int4        `json:"discount_percent"`
	DiscountValidUntil pgtype.Timestamptz `json:"discount_valid_until"`
	IsActive           pgtype.Bool        `json:"is_active"`
	IsDeleted          pgtype.Bool        `json:"is_deleted"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Review struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Rating    int32              `json:"rating"`
	Comment   pgtype.Text        `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Shipment struct {
	ID             pgtype.UUID        `json:"id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	Carrier        string             `json:"carrier"`
	TrackingNumber pgtype.Text        `json:"tracking_number"`
	Status         string             `json:"status"`
	ShippedAt      pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Email               string             `json:"email"`
	Password            string             `json:"password"`
	ProfilePictureUrl   pgtype.Text        `json:"profile_picture_url"`
	Role                UserRole           `json:"role"`
	Status              UserStatus         `json:"status"`
	IsVerified          pgtype.Bool        `json:"is_verified"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	LastPasswordChange  pgtype.Timestamptz `json:"last_password_change"`
	FailedLoginAttempts pgtype.Int4        `json:"failed_login_attempts"`
	LastFailedLogin     pgtype.Timestamptz `json:"last_failed_login"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type UserOtp struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Code       string             `json:"code"`
	Type       OtpType            `json:"type"`
	Channel    pgtype.Text        `json:"channel"`
	IsUsed     pgtype.Bool        `json:"is_used"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   pgtype.Int4        `json:"attempts"`
	LastSentAt pgtype.Timestamptz `json:"last_sent_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
