// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    product_id,
    sku,
    name,
    qty,
    unit_price_cents,
    total_price_cents
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, order_id, product_id, sku, name, qty, unit_price_cents, total_price_cents, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID         pgtype.UUID `json:"order_id"`
	ProductID       pgtype.UUID `json:"product_id"`
	Sku             pgtype.Text `json:"sku"`
	Name            pgtype.Text `json:"name"`
	Qty             int32       `json:"qty"`
	UnitPriceCents  int32       `json:"unit_price_cents"`
	TotalPriceCents int32       `json:"total_price_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.Qty,
		arg.UnitPriceCents,
		arg.TotalPriceCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Qty,
		&i.UnitPriceCents,
		&i.TotalPriceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, product_id, sku, name, qty, unit_price_cents, total_price_cents, created_at, updated_at FROM order_items
WHERE order_id = $1
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Qty,
			&i.UnitPriceCents,
			&i.TotalPriceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
