// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id,
    provider,
    provider_txn_id,
    amount_cents,
    currency,
    payment_method,
    status,
    details
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, order_id, provider, provider_txn_id, amount_cents, currency, payment_method, status, details, failure_reason, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID       pgtype.UUID `json:"order_id"`
	Provider      string      `json:"provider"`
	ProviderTxnID pgtype.Text `json:"provider_txn_id"`
	AmountCents   int64       `json:"amount_cents"`
	Currency      string      `json:"currency"`
	PaymentMethod string      `json:"payment_method"`
	Status        string      `json:"status"`
	Details       []byte      `json:"details"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Provider,
		arg.ProviderTxnID,
		arg.AmountCents,
		arg.Currency,
		arg.PaymentMethod,
		arg.Status,
		arg.Details,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderTxnID,
		&i.AmountCents,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.Details,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, provider, provider_txn_id, amount_cents, currency, payment_method, status, details, failure_reason, created_at, updated_at FROM payments
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderTxnID,
		&i.AmountCents,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.Details,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2, created_at = NOW()
WHERE id = $1
RETURNING id, order_id, provider, provider_txn_id, amount_cents, currency, payment_method, status, details, failure_reason, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Provider,
		&i.ProviderTxnID,
		&i.AmountCents,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.Details,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
