// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products WHERE is_deleted = FALSE
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    sku,
    name,
    description,
    category_id,
    price_cents,
    currency,
    attributes,
    main_image_url,
    images,
    discount_percent,
    discount_valid_until
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, sku, name, description, category_id, price_cents, currency, attributes, main_image_url, images, discount_percent, discount_valid_until, is_active, is_deleted, created_at, updated_at
`

type CreateProductParams struct {
	Sku                string             `json:"sku"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	PriceCents         int32              `json:"price_cents"`
	Currency           string             `json:"currency"`
	Attributes         []byte             `json:"attributes"`
	MainImageUrl       pgtype.Text        `json:"main_image_url"`
	Images             []byte             `json:"images"`
	DiscountPercent    pgtype.Int4        `json:"discount_percent"`
	DiscountValidUntil pgtype.Timestamptz `json:"discount_valid_until"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.PriceCents,
		arg.Currency,
		arg.Attributes,
		arg.MainImageUrl,
		arg.Images,
		arg.DiscountPercent,
		arg.DiscountValidUntil,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.PriceCents,
		&i.Currency,
		&i.Attributes,
		&i.MainImageUrl,
		&i.Images,
		&i.DiscountPercent,
		&i.DiscountValidUntil,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET is_deleted = TRUE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, sku, name, description, category_id, price_cents, currency, attributes, main_image_url, images, discount_percent, discount_valid_until, is_active, is_deleted, created_at, updated_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.PriceCents,
		&i.Currency,
		&i.Attributes,
		&i.MainImageUrl,
		&i.Images,
		&i.DiscountPercent,
		&i.DiscountValidUntil,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, sku, name, description, category_id, price_cents, currency, attributes, main_image_url, images, discount_percent, discount_valid_until, is_active, is_deleted, created_at, updated_at FROM products
WHERE sku = $1 LIMIT 1
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.PriceCents,
		&i.Currency,
		&i.Attributes,
		&i.MainImageUrl,
		&i.Images,
		&i.DiscountPercent,
		&i.DiscountValidUntil,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, sku, name, description, category_id, price_cents, currency, attributes, main_image_url, images, discount_percent, discount_valid_until, is_active, is_deleted, created_at, updated_at FROM products
WHERE is_deleted = FALSE
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.PriceCents,
			&i.Currency,
			&i.Attributes,
			&i.MainImageUrl,
			&i.Images,
			&i.DiscountPercent,
			&i.DiscountValidUntil,
			&i.IsActive,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    category_id = COALESCE($4, category_id),
    price_cents = COALESCE($5, price_cents),
    currency = COALESCE($6, currency),
    attributes = COALESCE($7, attributes),
    main_image_url = COALESCE($8, main_image_url),
    images = COALESCE($9, images),
    discount_percent = COALESCE($10, discount_percent),
    discount_valid_until = COALESCE($11, discount_valid_until),
    updated_at = NOW()
WHERE id = $1
RETURNING id, sku, name, description, category_id, price_cents, currency, attributes, main_image_url, images, discount_percent, discount_valid_until, is_active, is_deleted, created_at, updated_at
`

type UpdateProductParams struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	PriceCents         int32              `json:"price_cents"`
	Currency           string             `json:"currency"`
	Attributes         []byte             `json:"attributes"`
	MainImageUrl       pgtype.Text        `json:"main_image_url"`
	Images             []byte             `json:"images"`
	DiscountPercent    pgtype.Int4        `json:"discount_percent"`
	DiscountValidUntil pgtype.Timestamptz `json:"discount_valid_until"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.PriceCents,
		arg.Currency,
		arg.Attributes,
		arg.MainImageUrl,
		arg.Images,
		arg.DiscountPercent,
		arg.DiscountValidUntil,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.PriceCents,
		&i.Currency,
		&i.Attributes,
		&i.MainImageUrl,
		&i.Images,
		&i.DiscountPercent,
		&i.DiscountValidUntil,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductPrice = `-- name: UpdateProductPrice :one
UPDATE products
SET price_cents = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, sku, name, description, category_id, price_cents, currency, attributes, main_image_url, images, discount_percent, discount_valid_until, is_active, is_deleted, created_at, updated_at
`

type UpdateProductPriceParams struct {
	ID         pgtype.UUID `json:"id"`
	PriceCents int32       `json:"price_cents"`
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductPrice, arg.ID, arg.PriceCents)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.PriceCents,
		&i.Currency,
		&i.Attributes,
		&i.MainImageUrl,
		&i.Images,
		&i.DiscountPercent,
		&i.DiscountValidUntil,
		&i.IsActive,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
