// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReviewsByProduct = `-- name: CountReviewsByProduct :one
SELECT COUNT(*) FROM reviews
WHERE product_id = $1
`

func (q *Queries) CountReviewsByProduct(ctx context.Context, productID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
    product_id, user_id, rating, comment
)
VALUES (
    $1, $2, $3, $4
)
RETURNING id, product_id, user_id, rating, comment, created_at, updated_at
`

type CreateReviewParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews
WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReview = `-- name: GetReview :one
SELECT id, product_id, user_id, rating, comment, created_at, updated_at FROM reviews
WHERE id = $1
`

func (q *Queries) GetReview(ctx context.Context, id pgtype.UUID) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByUserAndProduct = `-- name: GetReviewByUserAndProduct :one
SELECT id, product_id, user_id, rating, comment, created_at, updated_at FROM reviews
WHERE user_id = $1 AND product_id = $2
LIMIT 1
`

type GetReviewByUserAndProductParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) GetReviewByUserAndProduct(ctx context.Context, arg GetReviewByUserAndProductParams) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByUserAndProduct, arg.UserID, arg.ProductID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewsByUser = `-- name: GetReviewsByUser :many
SELECT id, product_id, user_id, rating, comment, created_at, updated_at FROM reviews
WHERE user_id = $1
`

func (q *Queries) GetReviewsByUser(ctx context.Context, userID pgtype.UUID) ([]Review, error) {
	rows, err := q.db.Query(ctx, getReviewsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByProduct = `-- name: ListReviewsByProduct :many
SELECT id, product_id, user_id, rating, comment, created_at, updated_at FROM reviews
WHERE product_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReviewsByProductParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListReviewsByProduct(ctx context.Context, arg ListReviewsByProductParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByProduct, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET rating = $2,
    comment = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, product_id, user_id, rating, comment, created_at, updated_at
`

type UpdateReviewParams struct {
	ID      pgtype.UUID `json:"id"`
	Rating  int32       `json:"rating"`
	Comment pgtype.Text `json:"comment"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview, arg.ID, arg.Rating, arg.Comment)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
