// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shipments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (
    order_id, carrier, tracking_number, status, shipped_at, delivered_at
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, order_id, carrier, tracking_number, status, shipped_at, delivered_at, created_at, updated_at
`

type CreateShipmentParams struct {
	OrderID        pgtype.UUID        `json:"order_id"`
	Carrier        string             `json:"carrier"`
	TrackingNumber pgtype.Text        `json:"tracking_number"`
	Status         string             `json:"status"`
	ShippedAt      pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.OrderID,
		arg.Carrier,
		arg.TrackingNumber,
		arg.Status,
		arg.ShippedAt,
		arg.DeliveredAt,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNumber,
		&i.Status,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShipment = `-- name: DeleteShipment :exec
DELETE FROM shipments
WHERE id = $1
`

func (q *Queries) DeleteShipment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteShipment, id)
	return err
}

const getShipment = `-- name: GetShipment :one
SELECT id, order_id, carrier, tracking_number, status, shipped_at, delivered_at, created_at, updated_at FROM shipments
WHERE id = $1
`

func (q *Queries) GetShipment(ctx context.Context, id pgtype.UUID) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipment, id)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNumber,
		&i.Status,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShipmentsByOrder = `-- name: ListShipmentsByOrder :many
SELECT id, order_id, carrier, tracking_number, status, shipped_at, delivered_at, created_at, updated_at FROM shipments
WHERE order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListShipmentsByOrder(ctx context.Context, orderID pgtype.UUID) ([]Shipment, error) {
	rows, err := q.db.Query(ctx, listShipmentsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shipment{}
	for rows.Next() {
		var i Shipment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Carrier,
			&i.TrackingNumber,
			&i.Status,
			&i.ShippedAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShipmentStatus = `-- name: UpdateShipmentStatus :one
UPDATE shipments
SET status = $2,
    shipped_at = $3,
    delivered_at = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, order_id, carrier, tracking_number, status, shipped_at, delivered_at, created_at, updated_at
`

type UpdateShipmentStatusParams struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	ShippedAt   pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) UpdateShipmentStatus(ctx context.Context, arg UpdateShipmentStatusParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, updateShipmentStatus,
		arg.ID,
		arg.Status,
		arg.ShippedAt,
		arg.DeliveredAt,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Carrier,
		&i.TrackingNumber,
		&i.Status,
		&i.ShippedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
