// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_otps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserOTP = `-- name: CreateUserOTP :one
INSERT INTO user_otps (user_id, code, type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, code, type, channel, is_used, expires_at, attempts, last_sent_at, created_at, updated_at
`

type CreateUserOTPParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Code      string             `json:"code"`
	Type      OtpType            `json:"type"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserOTP(ctx context.Context, arg CreateUserOTPParams) (UserOtp, error) {
	row := q.db.QueryRow(ctx, createUserOTP,
		arg.UserID,
		arg.Code,
		arg.Type,
		arg.ExpiresAt,
	)
	var i UserOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Type,
		&i.Channel,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.Attempts,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM user_otps WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const getUserOTP = `-- name: GetUserOTP :one
SELECT id, user_id, code, type, channel, is_used, expires_at, attempts, last_sent_at, created_at, updated_at FROM user_otps
WHERE user_id = $1 AND type = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetUserOTPParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   OtpType     `json:"type"`
}

func (q *Queries) GetUserOTP(ctx context.Context, arg GetUserOTPParams) (UserOtp, error) {
	row := q.db.QueryRow(ctx, getUserOTP, arg.UserID, arg.Type)
	var i UserOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Type,
		&i.Channel,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.Attempts,
		&i.LastSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserOTPUsed = `-- name: MarkUserOTPUsed :exec
UPDATE user_otps SET used = TRUE WHERE id = $1
`

func (q *Queries) MarkUserOTPUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserOTPUsed, id)
	return err
}
