// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS total_count FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (first_name, last_name, email, password, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, first_name, last_name, email, password, profile_picture_url, role, status, is_verified, last_login_at, last_password_change, failed_login_attempts, last_failed_login, created_at, updated_at
`

type CreateUserParams struct {
	FirstName string   `json:"first_name"`
	LastName  string   `json:"last_name"`
	Email     string   `json:"email"`
	Password  string   `json:"password"`
	Role      UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.ProfilePictureUrl,
		&i.Role,
		&i.Status,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.LastPasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password, profile_picture_url, role, status, is_verified, last_login_at, last_password_change, failed_login_attempts, last_failed_login, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.ProfilePictureUrl,
		&i.Role,
		&i.Status,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.LastPasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, password, profile_picture_url, role, status, is_verified, last_login_at, last_password_change, failed_login_attempts, last_failed_login, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.ProfilePictureUrl,
		&i.Role,
		&i.Status,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.LastPasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, email, password, profile_picture_url, role, status, is_verified, last_login_at, last_password_change, failed_login_attempts, last_failed_login, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.ProfilePictureUrl,
			&i.Role,
			&i.Status,
			&i.IsVerified,
			&i.LastLoginAt,
			&i.LastPasswordChange,
			&i.FailedLoginAttempts,
			&i.LastFailedLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    profile_picture_url = COALESCE($4, profile_picture_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, email, password, profile_picture_url, role, status, is_verified, last_login_at, last_password_change, failed_login_attempts, last_failed_login, created_at, updated_at
`

type UpdateUserParams struct {
	ID                pgtype.UUID `json:"id"`
	FirstName         string      `json:"first_name"`
	LastName          string      `json:"last_name"`
	ProfilePictureUrl pgtype.Text `json:"profile_picture_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.ProfilePictureUrl,
		&i.Role,
		&i.Status,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.LastPasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
